#!/usr/bin/env python3
import json
import re
from pathlib import Path
from urllib.request import Request, urlopen


ROOT = Path.cwd()
STORE_PATH = ROOT / "js" / "store.js"
OUTPUT_PATH = ROOT / "js" / "skillmd-map.js"


def decode_readme_escaped(s: str) -> str:
    # 页面内 readme 是 JS 风格转义字符串，直接按 JSON 字符串解码可正确处理代理对 emoji
    safe = re.sub(r'\\(?!["\\/bfnrtu])', r"\\\\", s)
    try:
        return json.loads(f"\"{safe}\"")
    except Exception:
        # 容错回退：尽量恢复文本，避免因个别非法转义中断全量同步
        safe = re.sub(r"\\u([0-9a-fA-F]{4})", lambda m: chr(int(m.group(1), 16)), safe)
        safe = safe.replace("\\n", "\n").replace("\\r", "\r").replace("\\t", "\t")
        safe = safe.replace('\\"', '"').replace("\\\\", "\\")
        return safe


def build_human_summary(readme: str, fallback_title: str) -> str:
    lines = readme.split("\n")
    title = next((l for l in lines if l.startswith("# ")), f"# {fallback_title}")[2:].strip()
    quote = ""
    for l in lines:
        if l.strip().startswith(">"):
            quote = re.sub(r"^>\s*", "", l.strip())
            break

    headings = [re.sub(r"^##\s+", "", l).strip() for l in lines if re.match(r"^##\s+", l)][:6]
    bullets = [re.sub(r"^-\s+", "", l).strip() for l in lines if re.match(r"^-\s+", l)][:6]
    workflow = []
    for l in lines:
        m = re.match(r"^\d+\.\s+(.+)", l)
        if m:
            workflow.append(m.group(1).strip())
        if len(workflow) >= 6:
            break

    parts = [f"{title} 的官方 skill.md 要点如下："]
    if quote:
        parts.append(f"\n岗位定位：\n{quote}")
    if headings:
        parts.append("\n核心模块：\n" + "\n".join(f"• {h}" for h in headings))
    if bullets:
        parts.append("\n主要能力：\n" + "\n".join(f"• {b}" for b in bullets))
    if workflow:
        parts.append("\n工作步骤：\n" + "\n".join(f"{i+1}. {w}" for i, w in enumerate(workflow)))
    return "\n".join(parts)


def fetch_readme(slug: str):
    url = f"https://clawhub.ai/skills/{slug}"
    req = Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urlopen(req, timeout=30) as resp:
        html = resp.read().decode("utf-8", errors="ignore")
    m = re.search(r'readme:"((?:\\.|[^"\\])*)",readmeError:', html, re.S)
    if not m:
        raise RuntimeError("readme not found")
    return decode_readme_escaped(m.group(1)), url


def main():
    store = STORE_PATH.read_text(encoding="utf-8")
    slugs = sorted(set(re.findall(r"slug:\s*'([^']+)'", store)))
    skill_map = {}
    failed = []

    for slug in slugs:
        try:
            readme, source_url = fetch_readme(slug)
            skill_map[slug] = {
                "sourceUrl": source_url,
                "skillMdRaw": readme,
                "skillMdHuman": build_human_summary(readme, slug),
            }
            print(f"ok: {slug}")
        except Exception as e:
            failed.append({"slug": slug, "error": str(e)})
            print(f"fail: {slug} -> {e}")

    content = (
        "// Auto-generated by scripts/sync_skillmd.py\n"
        f"window.SkillMdMap = {json.dumps(skill_map, ensure_ascii=False, indent=2)};\n"
        f"window.SkillMdMapMeta = {json.dumps({'synced': len(skill_map), 'totalSlugs': len(slugs), 'failed': failed}, ensure_ascii=False, indent=2)};\n"
    )
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"\nwritten: {OUTPUT_PATH}")
    print(f"synced: {len(skill_map)}/{len(slugs)}")


if __name__ == "__main__":
    main()
