import fs from "fs/promises";
import path from "path";

const root = process.cwd();
const storePath = path.join(root, "js", "store.js");
const outputPath = path.join(root, "js", "skillmd-map.js");

function decodeReadmeEscaped(str) {
  return str
    .replace(/\\u([0-9a-fA-F]{4})/g, (_, h) => String.fromCharCode(parseInt(h, 16)))
    .replace(/\\n/g, "\n")
    .replace(/\\r/g, "\r")
    .replace(/\\t/g, "\t")
    .replace(/\\"/g, "\"")
    .replace(/\\\\/g, "\\");
}

function buildHumanSummary(readme, fallbackTitle) {
  const lines = readme.split("\n");
  const title = (lines.find((l) => l.startsWith("# ")) || `# ${fallbackTitle}`).replace(/^#\s*/, "");
  const quote = (lines.find((l) => l.trim().startsWith(">")) || "").replace(/^>\s*/, "").trim();
  const headings = lines
    .filter((l) => /^##\s+/.test(l))
    .map((l) => l.replace(/^##\s+/, "").trim())
    .slice(0, 6);

  const workflow = [];
  for (const line of lines) {
    const m = line.match(/^\d+\.\s+(.+)/);
    if (m) workflow.push(m[1].trim());
    if (workflow.length >= 6) break;
  }

  const bullets = [];
  for (const line of lines) {
    const m = line.match(/^-\s+(.+)/);
    if (m) bullets.push(m[1].trim());
    if (bullets.length >= 6) break;
  }

  const parts = [];
  parts.push(`${title} 的官方 skill.md 要点如下：`);
  if (quote) parts.push(`\n岗位定位：\n${quote}`);
  if (headings.length) parts.push(`\n核心模块：\n${headings.map((h) => `• ${h}`).join("\n")}`);
  if (bullets.length) parts.push(`\n主要能力：\n${bullets.map((b) => `• ${b}`).join("\n")}`);
  if (workflow.length) parts.push(`\n工作步骤：\n${workflow.map((w, i) => `${i + 1}. ${w}`).join("\n")}`);

  return parts.join("\n");
}

async function fetchReadme(slug) {
  const url = `https://clawhub.ai/skills/${slug}`;
  const res = await fetch(url, { redirect: "follow" });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const html = await res.text();
  const m = html.match(/readme:"((?:\\.|[^"\\])*)",readmeError:/s);
  if (!m) throw new Error("readme not found");
  return { readme: decodeReadmeEscaped(m[1]), sourceUrl: url };
}

async function main() {
  const store = await fs.readFile(storePath, "utf8");
  const slugs = Array.from(new Set([...store.matchAll(/slug:\s*'([^']+)'/g)].map((m) => m[1])));
  const map = {};
  const failed = [];

  for (const slug of slugs) {
    try {
      const { readme, sourceUrl } = await fetchReadme(slug);
      map[slug] = {
        sourceUrl,
        skillMdRaw: readme,
        skillMdHuman: buildHumanSummary(readme, slug),
      };
      console.log(`ok: ${slug}`);
    } catch (err) {
      failed.push({ slug, error: String(err.message || err) });
      console.log(`fail: ${slug} -> ${err.message || err}`);
    }
  }

  const content =
    `// Auto-generated by scripts/sync_skillmd.mjs\n` +
    `window.SkillMdMap = ${JSON.stringify(map, null, 2)};\n` +
    `window.SkillMdMapMeta = ${JSON.stringify(
      {
        generatedAt: new Date().toISOString(),
        totalSlugs: slugs.length,
        synced: Object.keys(map).length,
        failed,
      },
      null,
      2
    )};\n`;

  await fs.writeFile(outputPath, content, "utf8");
  console.log(`\nwritten: ${outputPath}`);
  console.log(`synced: ${Object.keys(map).length}/${slugs.length}`);
  if (failed.length) {
    console.log("failed list:");
    for (const f of failed) console.log(`- ${f.slug}: ${f.error}`);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});

